package(default_visibility = ["PUBLIC"])
python_library(
    name = "lib",
    srcs = glob(["**.py"]),
    deps = [
        "//third_party/python:standard_deps",
        "//src/python/splitgraph:lib",
        ],
)
